USER-SUPPLIED VALUES:
global:
  auth:
    backend:
      enabled: true
    environment: development
  clusterRouterBase: apps.dancurran-lab2025.opdev.io
  dynamic:
    plugins:
      #      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
      #        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tech-radar-backend-dynamic
        disabled: false
      - package: '@backstage-community/plugin-todo@0.2.42'
        disabled: false
        integrity: sha512-agmfwxHkZPy0zaXzjMKY9Us9l7J2og+z7p2lDWQBmlJ1KZRo6OBQdnlG1mTEryfEEl/bx5Ko+f1PhFj2/BmiIQ==
    includes:
      - dynamic-plugins.default.yaml
nameOverride: developer-hub
upstream:
  backstage:
    appConfig:
      techRadar:
        url: "test"
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
    extraEnvVars:
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: '{{ include "janus-idp.backend-secret-name" $ }}'
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: '{{- include "janus-idp.postgresql.secretName" . }}'
#    extraVolumeMounts:
#      - mountPath: /opt/app-root/src/dynamic-plugins-root
#        name: dynamic-plugins-root
#    extraVolumes:
#      - name: dynamic-plugins-root
#        persistentVolumeClaim:
#          claimName: '{{ printf "%s-dynamic-plugins-root" .Release.Name }}'
#      - name: npmcacache
    image:
      pullPolicy: Always
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9@sha256
      tag: d8268197ba0466643efb818fcad8f0fc29e32463f75b0f7f51d9ce75ec717572
  nameOverride: developer-hub
  #  postgresql:
  #    auth:
  #      secretKeys:
  #        adminPasswordKey: postgres-password
  #        userPasswordKey: password
  #    enabled: true
  #    image:
  #      registry: registry.redhat.io
  #      repository: rhel9/postgresql-15@sha256
  #      tag: 44a08b83a6c50714b52f4cf1c3476bc16b66faec21dd9a9bc07d1be5f97b8150
  #    postgresqlDataDir: /var/lib/pgsql/data/userdata
  #    primary:
  #      containerSecurityContext:
  #        enabled: false
  #      extraEnvVars:
  #      - name: POSTGRESQL_ADMIN_PASSWORD
  #        valueFrom:
  #          secretKeyRef:
  #            key: postgres-password
  #            name: '{{- include "postgresql.v1.secretName" . }}'
  #      persistence:
  #        enabled: true
  #        mountPath: /var/lib/pgsql/data
  #        size: 1Gi
  #      podSecurityContext:
  #        enabled: false
  #      resources:
  #        limits:
  #          cpu: 250m
  #          ephemeral-storage: 20Mi
  #          memory: 1024Mi
  #        requests:
  #          cpu: 250m
  #          memory: 256Mi
  #  service:
  #    externalTrafficPolicy: Cluster
  #    extraPorts:
  #    - name: http-metrics
  #      port: 9464
  #      targetPort: 9464
  #    ports:
  #      backend: 7007
  #      name: http-backend
  #      targetPort: backend
  #    sessionAffinity: None
  #    type: ClusterIP
#  serviceAccount:
#    automountServiceAccountToken: true
#    create: false
